module.exports = function() {
return `` +
`<div>
    <div>
        <h2>Business History</h2>
        <p>ASIDACO was legally registered on September 24 2008. Based on ideas, meetings and accomplishments started in 2004. The founder is passionate about Alternative ways to produce energy, principles in science, design, and construction, and the progression of these forward in industry. Her passion for technology, humanity, and social well-being has been a prime motivation to found ASIDACO. The business has been founded with intent to perform at the highest integrity and levels in order to achieve the completion of projects that serve the end user successfully. Andrea Bashaw has founded ASIDACO with the vision of achieving success as a leader in the energy and sustainable community services arena. The business plan encompasses technological design, manufacturing, construction, and system operations with a focus on energy production, distribution, and integration services. Presently ASIDACO acts as an ‘Owners Representative’ consultant for project development. We are a visionary and knowledge-based venture, incorporating a broad spectrum of expertise aimed toward workable and sustainable energy and design solutions for both client and environment.</p>
        <p>The company is located in Dayton, Ohio.</p>
    </div>
    <div>
        <h2>About the Founder</h4>
        <p>This passion to design and build started as a young adult. Andrea’s first accomplishment for this was achieved during the early 1980s while applying her insight and skills to develop a small distributed power plant, while utilizing and rebuilding stabilization components for that system at an industrial facility. She managed this facility’s operation and maintenance for many continued years post construction. Andrea was also the founding principle member of an electrical contracting company and was the youngest to receive an electrical contractor’s license in the city of Dayton Ohio at that time. She has always loved communicating with people and inspiring them to think outside the box. This included new ways to do things, or the creation of a new system, community, or product. Andrea enjoys brainstorming and producing a ‘Think Tank’ approach to solve solutions for construction projects, and energy needs that the population faces. Keen intuitiveness serves the founder to see problems and benefits to an idea prior to constructing the subject matter. She serves clients well with the ability to see both sides of a situation and help to foster a resolution between two parties for a long-term outcome.</p>
    </div>
</div>`
}